steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-southwest1-docker.pkg.dev/tienda-microservices-427314/image-registry/products-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-southwest1-docker.pkg.dev/tienda-microservices-427314/image-registry/products-ms",
      ]
      
options:
  logging: CLOUD_LOGGING_ONLY